//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distic.Employability.Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Distic.Employability.Calculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a free software tool developed by Distic. You are permitted to use the program or code for any purpose..
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Employability Calculator.
        /// </summary>
        internal static string AboutEmployabilityCalculator {
            get {
                return ResourceManager.GetString("AboutEmployabilityCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employability Calculator by Distic.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Window Size.
        /// </summary>
        internal static string AssignWindowSize {
            get {
                return ResourceManager.GetString("AssignWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2019 Distic. All rights reserved..
        /// </summary>
        internal static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distic Employability Calculator.
        /// </summary>
        internal static string DisticEmployabilityCalculator {
            get {
                return ResourceManager.GetString("DisticEmployabilityCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://distic.com.
        /// </summary>
        internal static string DisticLink {
            get {
                return ResourceManager.GetString("DisticLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the trainer file is busted, make sure the data is inserted correctly and try again..
        /// </summary>
        internal static string FileCannotBeRead {
            get {
                return ResourceManager.GetString("FileCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/distic.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        internal static string HeightCol {
            get {
                return ResourceManager.GetString("HeightCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_AboutPlaceholderLogo {
            get {
                object obj = ResourceManager.GetObject("Img_AboutPlaceholderLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EccpuTrainer.json.
        /// </summary>
        internal static string JsonFilename {
            get {
                return ResourceManager.GetString("JsonFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message From Programmer Dude.
        /// </summary>
        internal static string MessageFromProgrammerDude {
            get {
                return ResourceManager.GetString("MessageFromProgrammerDude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer file cannot be found, make sure that the &quot;EccpuTrainer.json&quot; file is located in the same directory of the running program!.
        /// </summary>
        internal static string TrainerFileCannotBeFound {
            get {
                return ResourceManager.GetString("TrainerFileCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit us on GitHub.
        /// </summary>
        internal static string VisitUsOnGitHub {
            get {
                return ResourceManager.GetString("VisitUsOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        internal static string WidthCol {
            get {
                return ResourceManager.GetString("WidthCol", resourceCulture);
            }
        }
    }
}
