//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distic.Employability.Calculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("177, 127, 42")]
        public global::System.Drawing.Color ECButtonBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ECButtonBackColor"]));
            }
            set {
                this["ECButtonBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("201, 230, 143")]
        public global::System.Drawing.Color ECOutputFrameBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ECOutputFrameBackColor"]));
            }
            set {
                this["ECOutputFrameBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ECButtonForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ECButtonForeColor"]));
            }
            set {
                this["ECButtonForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("177, 147, 42")]
        public global::System.Drawing.Color ECButtonBackColorHover {
            get {
                return ((global::System.Drawing.Color)(this["ECButtonBackColorHover"]));
            }
            set {
                this["ECButtonBackColorHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87, 78")]
        public global::System.Drawing.Size ECButtonRectSize {
            get {
                return ((global::System.Drawing.Size)(this["ECButtonRectSize"]));
            }
            set {
                this["ECButtonRectSize"] = value;
            }
        }
    }
}
